export const BTN_CLICKED_REQUEST = 'BTN_CLICKED_REQUEST'
export const BTN_CLICKED_SUCCESS = 'BTN_CLICKED_SUCCESS'
export const BTN_CLICKED_FAILURE = 'BTN_CLICKED_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const EDIT_REQUEST = 'EDIT_REQUEST'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_FAILURE = 'EDIT_FAILURE'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE'
